name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GolangCI-Lint Action
        uses: matoous/golangci-lint-action@v1.23.3
